Gcode support
v1r0x/files_3d pull request #38
Opened 2021-04-04 21:43 UTC by csicar

![gcode-preview](https://user-images.githubusercontent.com/725406/113522283-80500a80-959f-11eb-9a82-a5f8cc0dc5e2.png)

2021-04-04 21:43 UTC, csicar commented
this is based on #37 . Once that is merged, i'll rebase this PR

2021-04-06 08:40 UTC, v1r0x requested changes

2021-04-06 08:40 UTC, v1r0x commented on src/components/Files3d.vue
> +			console.log("show gocede!", path)
Remove this please :wink:

2021-06-01 12:53 UTC, v1r0x approved these changes

2021-06-01 12:53 UTC, merged